# name: Move assigned pull requests into To do

# on:
#   pull_request:
#     types: [assigned]

# jobs:
#   automate-project-columns:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: alex-page/github-project-automation-plus@v0.8.3
#         with:
#           project: Backlog
#           column: To do
#           repo-token: ${{ secrets.GITHUB_TOKEN }}

name: testing jira inputs from issue

on: 
  workflow_dispatch:
    inputs:
      changelog: 
        type: string
        required: false
jobs:
  debugInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Var1: $changelog"


env:
  changelog: ${{ inputs.changelog }}
